import { Link } from 'libframe-docs/components'

We may wonder, why not using `throw new Error()` instead of `throw new Abort()`?

```js
// TodoList.telefunc.js
// Environment: Node.js

import { getContext } from 'telefunc'

export async function getTodoList() {
  const { user } = getContext()

  if (!user) {
    // Instead of `throw Abort()`
    throw new Error()
  }

  // ...
}
```

In principle, it also works as `throw new Error()` also achieves the job of canceling the telefunction. But `Abort()` comes with many conveniences and we therefore recommend using `throw Abort()`.

In general:
 - We use **`throw Abort()`** for errors originating from a **wrong public usage** of a telefunction.
 - We use **`throw new Error()`** for errors originating from a **wrong internal usage** of a function.

For example:

```js
// auth/getUser.ts
// Environment: Node.js

// Note that `auth/getUser.ts` is not a `.telefunc.js` file (`getUser()` is
// not a telefunction but a so-called `getContext()` wrapper).
export { getUser }

import { Abort, getContext } from 'telefunc'

function getUser({ permission }) {
  if (!permission) {
    throw new Error('Wrong getUser() usage: missing permission')
  }
  // We avoid typos (a typo like `admni` could have dramatic consequences)
  if (!['public', 'admin'].includes(permission)) {
    throw new Error('Wrong getUser() usage: unknown permission ' + permission)
  }

  const { user } = getContext()

  if (!user) {
    throw Abort()
  }

  if (permission === 'admin') {
    if (!user.isAdmin) {
      throw Abort()
    }
    return user
  }

  if (permission === 'public') {
    return user
  }
}
```

> Such `getContext()` wrapper is a common Telefunc technique explained at <Link href="/permissions#getcontext-wrappers" doNotInferSectionTitle={true} />.

```js
// components/Comment.telefunc.js
// Environment: Node.js

import { getUser } from '../auth/getUser'
import { shield } from 'telefunc'

shield(onCommentDelete, [shield.type.number])
export async function onCommentDelete(id) {
  // Only admins are allowed to delete a comment
  const user = getUser({ permission: 'admin' })
  const comment = await Comment.findOne({ id })
  await comment.delete()
}
```

It is expected that `throw Abort()` can occur, since `onCommentDelete()` is a public function anyone can call while not being an admin.

Whereas `throw new Error('Wrong getUser() usage')` is expected to *not* occur: if we make a typo and call `getUser({ permission: 'admni' })` then it's an internal bug in our backend that we should fix.
